site_name: 'Soulweb Docs'
site_url: 'http://docs.soulweb.it'

site_description: 'Soulweb Team Documentation'
site_author: 'Soulweb Solutions Ltd.'

repo_name: 'mecmartini/soulweb-docs'
repo_url: 'https://github.com/mecmartini/soulweb-docs'

pages:
- Home: 'index.md'
- Drupal 8:
  - Development Workflow: 'drupal/drupal_development_workflow.md'
  - Local Development:
    - macOS:
      - Vagrant:
        - Drupal VM: 'drupal/drupal_vm.md'
        - PhpStorm: 'drupal/drupal_vm_phpstorm.md'
        - Xdebug: 'drupal/drupal_vm_xdebug.md'
        - Coder Sniffer: 'drupal/drupal_vm_codersniffer.md'
        - ESLint: 'drupal/drupal_vm_eslint.md'
        - Pre Commit Hook: 'drupal/drupal_vm_precommit.md'
        - PHPUnit: 'drupal/drupal_vm_phpunit.md'
        - Functional Javascript Testing: 'drupal/drupal_vm_functionaljavascript.md'
        - BDD with Behat: 'drupal/drupal_vm_behat.md'
        - Responsive Testing with Galen: 'drupal/drupal_vm_galen.md'
    - Docker:
      - Setup:
        - Ubuntu: 'drupal/docker/setup-ubuntu.md'
        - MacOs: 'drupal/docker/setup-macos.md'
  - Basic Configuration: 'drupal/drupal_basic_configuration.md'
  - Using Composer: 'drupal/drupal_composer.md'
  - Configuration Management (CMI): 'drupal/drupal_configuration_management.md'
  - Deploy Content: 'drupal/drupal_deploy_content.md'
  - CORS Configuration: 'drupal/drupal_cors.md'
  - Multisite: 'drupal/drupal_multisite.md'
  - Theme Development:
    - Bootstrap (SASS) sub-theme: 'drupal/drupal_bootstrap_sass.md'
    - Component based theme using UI-Patterns: 'drupal/drupal_ui_patterns.md'

theme: 'material'

extra:
  logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'cyan'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: True
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

copyright: 'Copyright &copy; 2017 Soulweb Solutions Ltd.'
google_analytics: ['UA-99054399-1', 'docs.soulweb.it']